"""Created ev_opportunities table

Revision ID: 09ec023e1370
Revises: de52fda6dd89
Create Date: 2026-02-05 00:31:07.458129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ec023e1370'
down_revision: Union[str, Sequence[str], None] = 'de52fda6dd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('true_probability_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('ev_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('edge', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('is_positive_ev', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['true_probability_id'], ['true_probabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_id', 'true_probability_id', name='uq_price_trueprob')
    )
    op.create_index(op.f('ix_ev_opportunities_id'), 'ev_opportunities', ['id'], unique=False)
    op.create_index('ix_evopp_snapshot_book', 'ev_opportunities', ['odds_snapshot_id', 'sportsbook_id'], unique=False)
    op.create_index('ix_evopp_snapshot_ev', 'ev_opportunities', ['odds_snapshot_id', 'ev_pct'], unique=False)
    op.drop_constraint('uq_snapshot_market_outcome_point', 'true_probabilities', type_='unique')
    op.create_unique_constraint('uq_snapshot_market_outcome_point_method', 'true_probabilities', ['odds_snapshot_id', 'market_id', 'outcome_name', 'outcome_point', 'method'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_market_outcome_point_method', 'true_probabilities', type_='unique')
    op.create_unique_constraint('uq_snapshot_market_outcome_point', 'true_probabilities', ['odds_snapshot_id', 'market_id', 'outcome_name', 'outcome_point'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_evopp_snapshot_ev', table_name='ev_opportunities')
    op.drop_index('ix_evopp_snapshot_book', table_name='ev_opportunities')
    op.drop_index(op.f('ix_ev_opportunities_id'), table_name='ev_opportunities')
    op.drop_table('ev_opportunities')
    # ### end Alembic commands ###
