"""Renamed fields

Revision ID: 4fc821e5ebd5
Revises: 3e8ecbe0c2d5
Create Date: 2026-01-26 18:38:06.708314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc821e5ebd5'
down_revision: Union[str, Sequence[str], None] = '3e8ecbe0c2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('league_name', sa.String(), nullable=False))
    op.drop_constraint('uq_name_sport', 'leagues', type_='unique')
    op.create_unique_constraint('uq_league_name_sport', 'leagues', ['league_name', 'sport_id'])
    op.drop_column('leagues', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_league_name_sport', 'leagues', type_='unique')
    op.create_unique_constraint('uq_name_sport', 'leagues', ['name', 'sport_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('leagues', 'league_name')
    # ### end Alembic commands ###
