"""Odds Ingestion Tables created

Revision ID: 6eb0273e5ecc
Revises: 1ac6d45b49a3
Create Date: 2026-01-22 22:00:49.539674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eb0273e5ecc'
down_revision: Union[str, Sequence[str], None] = '1ac6d45b49a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulled_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_id'), 'odds_snapshots', ['id'], unique=False)
    op.create_index('ix_source_pulledat', 'odds_snapshots', ['source', 'pulled_at'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sports_id'), 'sports', ['id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league_abv', sa.String(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_abv', 'sport_id', name='uq_leagueabv_sport'),
    sa.UniqueConstraint('name', 'sport_id', name='uq_name_sport')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('team_abv', sa.String(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_abv', 'league_id', name='uq_teamabv_league'),
    sa.UniqueConstraint('team_name', 'league_id', name='uq_team_league')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', name='uq_source_event')
    )
    op.create_index('ix_awayteam', 'events', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index('ix_hometeam', 'events', ['home_team_id'], unique=False)
    op.create_index('ix_league_starttime', 'events', ['league_id', 'start_time'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'market_type', 'period', 'line', name='uq_event_market_period_line')
    )
    op.create_index('ix_event', 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('american_odds', sa.Integer(), nullable=False),
    sa.Column('outcome_name', sa.String(), nullable=False),
    sa.Column('outcome_point', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['odds_snapshots.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'sportsbook_id', 'snapshot_id', 'outcome_name', 'outcome_point', name='uq_market_sportsbook_snapshot_outcome')
    )
    op.create_index('ix_market', 'prices', ['market_id'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index('ix_snapshot', 'prices', ['snapshot_id'], unique=False)
    op.create_index('ix_sportsbook', 'prices', ['sportsbook_id'], unique=False)
    op.add_column('sportsbooks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sportsbooks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'sportsbooks', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sportsbooks', type_='unique')
    op.alter_column('sportsbooks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('sportsbooks', 'updated_at')
    op.drop_index('ix_sportsbook', table_name='prices')
    op.drop_index('ix_snapshot', table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('ix_market', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index('ix_event', table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_league_starttime', table_name='events')
    op.drop_index('ix_hometeam', table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_awayteam', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_sports_id'), table_name='sports')
    op.drop_table('sports')
    op.drop_index('ix_source_pulledat', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    # ### end Alembic commands ###
