"""Refined fields across prices & ev_opportunities

Revision ID: 808811bd3217
Revises: 09ec023e1370
Create Date: 2026-02-18 02:49:22.077880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "808811bd3217"
down_revision: Union[str, Sequence[str], None] = "09ec023e1370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ev_opportunities",
        sa.Column("ev_per_dollar", sa.Numeric(precision=10, scale=6), nullable=False),
    )
    op.drop_index("ix_evopp_snapshot_ev", table_name="ev_opportunities")
    op.create_index(
        "ix_evopp_snapshot_ev",
        "ev_opportunities",
        ["odds_snapshot_id", "ev_per_dollar"],
        unique=False,
    )
    op.drop_column("ev_opportunities", "ev_pct")
    op.add_column("prices", sa.Column("odds_snapshot_id", sa.Integer(), nullable=False))
    op.drop_index("ix_snapshot", table_name="prices")
    op.create_index("ix_snapshot", "prices", ["odds_snapshot_id"], unique=False)
    op.drop_constraint(
        "uq_market_sportsbook_snapshot_outcome", "prices", type_="unique"
    )
    op.create_unique_constraint(
        "uq_market_sportsbook_snapshot_outcome",
        "prices",
        [
            "market_id",
            "sportsbook_id",
            "odds_snapshot_id",
            "outcome_name",
            "outcome_point",
        ],
    )
    op.drop_constraint("prices_snapshot_id_fkey", "prices", type_="foreignkey")
    op.create_foreign_key(
        "prices_odds_snapshot_id_fkey",
        "prices",
        "odds_snapshots",
        ["odds_snapshot_id"],
        ["id"],
    )
    op.drop_column("prices", "snapshot_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prices",
        sa.Column("snapshot_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("prices_odds_snapshot_id_fkey", "prices", type_="foreignkey")
    op.create_foreign_key(
        "prices_snapshot_id_fkey", "prices", "odds_snapshots", ["snapshot_id"], ["id"]
    )
    op.drop_constraint(
        "uq_market_sportsbook_snapshot_outcome", "prices", type_="unique"
    )
    op.create_unique_constraint(
        "uq_market_sportsbook_snapshot_outcome",
        "prices",
        ["market_id", "sportsbook_id", "snapshot_id", "outcome_name", "outcome_point"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index("ix_snapshot", table_name="prices")
    op.create_index("ix_snapshot", "prices", ["snapshot_id"], unique=False)
    op.drop_column("prices", "odds_snapshot_id")
    op.add_column(
        "ev_opportunities",
        sa.Column(
            "ev_pct",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_evopp_snapshot_ev", table_name="ev_opportunities")
    op.create_index(
        "ix_evopp_snapshot_ev",
        "ev_opportunities",
        ["odds_snapshot_id", "ev_pct"],
        unique=False,
    )
    op.drop_column("ev_opportunities", "ev_per_dollar")
    # ### end Alembic commands ###
