"""Modified sportbooks table

Revision ID: a8b0740106e3
Revises: 4fc821e5ebd5
Create Date: 2026-01-26 19:49:17.897266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b0740106e3'
down_revision: Union[str, Sequence[str], None] = '4fc821e5ebd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportsbooks', sa.Column('sportsbook_name', sa.String(), nullable=False))
    op.add_column('sportsbooks', sa.Column('sportsbook_display_name', sa.String(), nullable=False))
    op.add_column('sportsbooks', sa.Column('region', sa.String(), nullable=False))
    op.add_column('sportsbooks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint('sportsbooks_name_key', 'sportsbooks', type_='unique')
    op.create_unique_constraint(None, 'sportsbooks', ['sportsbook_name'])
    op.drop_column('sportsbooks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sportsbooks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sportsbooks', type_='unique')
    op.create_unique_constraint('sportsbooks_name_key', 'sportsbooks', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('sportsbooks', 'is_active')
    op.drop_column('sportsbooks', 'region')
    op.drop_column('sportsbooks', 'sportsbook_display_name')
    op.drop_column('sportsbooks', 'sportsbook_name')
    # ### end Alembic commands ###
