"""Add true probs table

Revision ID: de52fda6dd89
Revises: f805d6bd13e0
Create Date: 2026-01-30 14:15:09.659327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de52fda6dd89'
down_revision: Union[str, Sequence[str], None] = 'f805d6bd13e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('true_probabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome_name', sa.String(), nullable=False),
    sa.Column('outcome_point', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('true_prob', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odds_snapshot_id', 'market_id', 'outcome_name', 'outcome_point', name='uq_snapshot_market_outcome_point')
    )
    op.create_index('ix_market_snapshot', 'true_probabilities', ['market_id', 'odds_snapshot_id'], unique=False)
    op.create_index(op.f('ix_true_probabilities_id'), 'true_probabilities', ['id'], unique=False)
    op.create_index(op.f('ix_true_probabilities_market_id'), 'true_probabilities', ['market_id'], unique=False)
    op.create_index(op.f('ix_true_probabilities_odds_snapshot_id'), 'true_probabilities', ['odds_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_true_probabilities_odds_snapshot_id'), table_name='true_probabilities')
    op.drop_index(op.f('ix_true_probabilities_market_id'), table_name='true_probabilities')
    op.drop_index(op.f('ix_true_probabilities_id'), table_name='true_probabilities')
    op.drop_index('ix_market_snapshot', table_name='true_probabilities')
    op.drop_table('true_probabilities')
    # ### end Alembic commands ###
