"""Changed nullable for outcome_point in Price

Revision ID: f805d6bd13e0
Revises: edfb2ab29d7b
Create Date: 2026-01-27 20:53:36.970487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f805d6bd13e0'
down_revision: Union[str, Sequence[str], None] = 'edfb2ab29d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'outcome_point',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'outcome_point',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               nullable=False)
    # ### end Alembic commands ###
